version: "3.9"

services:
  summarizer:
    build:
      context: .
      dockerfile: Dockerfile
    image: soyo-summarizer:main
    container_name: summarizer
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase.json
      - PYTHONWARNINGS=ignore:.*do_sample.*:UserWarning,ignore:.*top_p.*:UserWarning,ignore:.*top_k.*:UserWarning
    volumes:
      - ./secrets/firebase.json:/app/firebase.json:ro
      - hf:/root/.cache/huggingface
    # Dockerfile CMD를 무시하고 명확히 실행 커맨드 지정
    command: ["python","-u","/app/realtime_summarizer.py","--batch-size","10","--write"]
    restart: unless-stopped

volumes:
  hf:
